# Generated by Django 2.0.7 on 2018-07-05 16:30

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('density', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('count', models.IntegerField()),
                ('activity_ts', models.DateTimeField()),
                ('space', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='density.Space')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='dpu_activity',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='dpu_activity',
            name='dpu',
        ),
        migrations.RemoveField(
            model_name='dpu_activity',
            name='space',
        ),
        migrations.DeleteModel(
            name='DPU_Activity',
        ),
        migrations.AlterIndexTogether(
            name='space_activity',
            index_together={('space', 'activity_ts')},
        ),
    ]
