# Generated by Django 2.0.7 on 2018-07-06 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('density', '0003_doorway_dpu_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space_activity',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='density.Space'),
        ),
    ]
